### ISSUE TITLE
annotation on shape

### ISSUE THREAD

**Issue by jessevdam** [shexSpec/shex.js#17]
Either the implementation and/or the spec in incomplete/buggy on annotations for shapes. 

In the spec there is 

> Annotations provide a format-independent way to provide additional information about elements in a schema. They appear in lists in Shape, OneOf, EachOf and TripleConstraint's annotations. 

and there is 

> [18]    	shapeDefinition 	   ::=    	(extraPropertySet | "CLOSED")* "{" tripleExpression? "}" annotation* semanticActions

However the Shape in the ShexR and json has no property for annotation, but the EachOf can have an annotation. So the shape annotation can be moved the EachOf object.

However when running the following code

```
PREFIX : <http://hl7.org/fhir/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

start = @<ObservationShape>

<ObservationShape> {          
  :status xsd:integer;
}
// :test "val"
```
Gives 

> error parsing input schema:
> Error: unknown property: "annotations" in Shape: {"type":"Shape","expression":{"type":"TripleConstraint","predicate":"http://hl7.org/fhir/status","valueExpr":{"type":"NodeConstraint","datatype":"http://www.w3.org/2001/XMLSchema#integer"}},"annotations":[{"type":"Annotation","predicate":"http://hl7.org/fhir/test","object":{"value":"val"}}]}

Additionally I would prefer if the syntax would look like as
```
<ObservationShape> {          
  // :test "val"
  :status xsd:integer;
}

```

**Comment by ericprud** [comment]
fixed in https://github.com/shexSpec/shex.js/commit/c008d62c0e38677ce8ea8147983b25682f4f5b61

and yeah, your alternative syntax does make more sense.
