### ISSUE TITLE
Named shape with AND, OR statements fails

### ISSUE THREAD

**Issue by jessevdam** [shexSpec/shex.js#18]
Given data:

```
PREFIX : <http://hl7.org/fhir/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

<Obs1>
  :base    "final" ;
  :a   "a" .
```

Then this schema works as expected

```
PREFIX : <http://hl7.org/fhir/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

start = @<Test>

<Test> {             
  :base xsd:string; 
} 
 AND ({
  :a xsd:string;
} OR
 {
  :b xsd:string;
})

```
However if I used named shapes it does not work anymore

```
PREFIX : <http://hl7.org/fhir/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

start = @<Test>

<Test> {            
  :base xsd:string; 
} 
 AND (<SubTestA> OR <SubTestB>)

<SubTestA> {
  :a xsd:string;
}


<SubTestB> {
  :b xsd:string;
}

```

**Comment by ericprud** [comment]
Note that `(<SubTestA> OR <SubTestB>)` is looking for one of two datatypes. I think you want `(@<SubTestA> OR @<SubTestB>)`.
[This rawgit invocation](http://rawgit.com/shexSpec/shex.js/master/doc/shex-simple.html?schema=PREFIX%20%3A%20%3Chttp%3A%2F%2Fhl7.org%2Ffhir%2F%3E%0APREFIX%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0Astart%20%3D%20%40%3CTest%3E%0A%0A%3CTest%3E%20%7B%20%3Abase%20xsd%3Astring%3B%20%7D%20%0A%20AND%20(%0A%23%20%7B%20%3Aa%20xsd%3Astring%3B%20%7D%20OR%20%7B%20%3Ab%20xsd%3Astring%3B%20%7D%0A%20%20%40%3CSubTestA%3E%20OR%20%40%3CSubTestB%3E%0A)%0A%0A%3CSubTestA%3E%20%7B%20%3Aa%20xsd%3Astring%3B%20%7D%0A%3CSubTestB%3E%20%7B%20%3Ab%20xsd%3Astring%3B%20%7D&data=PREFIX%20%3A%20%3Chttp%3A%2F%2Fhl7.org%2Ffhir%2F%3E%0A%0A%3CObs1%3E%0A%20%20%3Abase%20%20%20%20%22final%22%20%3B%0A%20%20%3Aa%20%20%20%22a%22%20.&shape-map=http%3A%2F%2Fa.example%2FObs1%40-%20start%20-) indicates this is currently working.

**Comment by jessevdam** [comment]
Sorry my fault, I did not realize i was creating a date type constraint, however i am afraid not the only person going to make this error. So maybe the implementation could give a warning if data type constraint points to data type that is also defined as a shape.
