### ISSUE TITLE
json-to-shex doesn't recognize Shape.expression property

### ISSUE THREAD

**Issue by phtyson** [shexSpec/shex.js#199]
Using shex@1.0.0-alpha.24 from npm.

When I run shex-to-json on
`{
  "type": "Schema",
  "shapes": [
    {
      "type": "Shape",
      "expression": {
        "type": "TripleConstraint",
        "predicate": "http://schema.example/#empID",
        "valueExpr": {
          "type": "NodeConstraint",
          "datatype": "http://www.w3.org/2001/XMLSchema#integer"
        }
      }
    }
  ]
}`
(Example reduced from a sample in ShEx 2.1 spec.)
I get:
`aborting: Error: error parsing JSON file://C:\path\to\shex\example-shex.json: Error: unknown property: "expression" in ShapeDecl: {"type":"Shape","expression":{"type":"TripleConstraint","predicate":"http://schema.example/#empID","valueExpr":{"type":"NodeConstraint","datatype":"http://www.w3.org/2001/XMLSchema#integer"}}}
    at parseShExJ (C:\path\to\node_modules\@shexjs\loader\shex-loader.js:280:18)
    at loadParseMergeSchema (C:\path\to\node_modules\@shexjs\loader\shex-loader.js:189:22)
`
Expected ShExC output without error.
Same error from same input on https://rawgit.com/shexSpec/shex.js/main/packages/shex-webapp/doc/shex-simple.html

**Comment by ericprud** [comment]
Hmm, I'm confused. I'd have expected that shape to have an ID, e.g.:
``` diff
 {
   "type": "Schema",
   "shapes": [
     {
       "type": "Shape",
+      "id": "http://a.example/myShape",
       "expression": {
         "type": "TripleConstraint",
         "predicate": "http://schema.example/#empID",
         "valueExpr": {
           "type": "NodeConstraint",
           "datatype": "http://www.w3.org/2001/XMLSchema#integer"
         }
       }
     }
   ]
 }
```

We updated the ShExJ to accomodate EXTENDS (and make a bunch of stuff simpler). As a result, that ShExJ is now (using my invented name):
``` json
{
  "type": "Schema",
  "shapes": [
    {
      "type": "ShapeDecl",
      "id": "http://a.example/myShape",
      "shapeExpr": {
        "type": "Shape",
        "expression": {
          "type": "TripleConstraint",
          "predicate": "http://schema.example/#empID",
          "valueExpr": {
            "type": "NodeConstraint",
            "datatype": "http://www.w3.org/2001/XMLSchema#integer"
          }
        }
      }
    }
  ]
}
```
[[try it](http://shex.io/webapps/shex.js/doc/shex-simple?schema=%7B%0A%20%20%22type%22%3A%20%22Schema%22%2C%0A%20%20%22shapes%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22type%22%3A%20%22ShapeDecl%22%2C%0A%20%20%20%20%20%20%22id%22%3A%20%22http%3A%2F%2Fa.example%2FmyShape%22%2C%0A%20%20%20%20%20%20%22shapeExpr%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22type%22%3A%20%22Shape%22%2C%0A%20%20%20%20%20%20%20%20%22expression%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22TripleConstraint%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22predicate%22%3A%20%22http%3A%2F%2Fschema.example%2F%23empID%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22valueExpr%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22NodeConstraint%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22datatype%22%3A%20%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23integer%22%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%5D%0A%7D&manifestURL=http%3A%2F%2Fshex.io%2Fwebapps%2Fshex.js%2Fexamples%2Fmanifest.json&interface=human&success=proof&regexpEngine=eval-threaded-nerr)]

**Comment by ericprud** [comment]
Yeah, sorry, that's in http://shex.io/shex-next/#dfn-shapedecl (see [ShExJ](http://shex.io/shex-next/#shexj) for context), which is linked from shex.io under "upcoming specs". I'm about to get on a train. I'll make sure shex.js is backward-compatible by the time I get off.

**Comment by ericprud** [comment]
It looks like I did this but forgot to notify you. Sorry!
