### ISSUE TITLE
Duplicate shape option not specific enough

### ISSUE THREAD

**Issue by hsolbrig** [shexSpec/shex.js#3]
The "--duplicate-shape fred" option (I guess one string is as good as another) causes the parser to ignore duplicate shapes across _and within_ shape definition files.  We need an option that causes the parser to ignore duplicates if we happen to send the same or similar shape definition across two invocations.   We do not, however, want to ignore two definitions of the same shape _within_ the same same call.

Suggestion: the caching of definitions should be changed to an "opt in"  approach.  Don't cache a shape definition unless the caller specifically says "I want you to hang on to this".

**Comment by ericprud** [comment]
Note that --duplicate-shape options are ignore|replace|abort . Is any other behavior desired?

**Comment by hsolbrig** [comment]
Resolved -- behavior options cover my use case
