### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by egonw** [shexSpec/shex.js#36]
When I run `npm install shex.js` (as in README), I get this error message:

```
$ npm install shex.js
npm ERR! code E404
npm ERR! 404 Not Found: shex.js@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-09-22T12_30_45_453Z-debug.log
```

**Comment by ericprud** [comment]
I've not been able to replicate this bug. Can you try `npm cache verify` and, if that doesn't work, `npm cache clean`, to see if it's a cache issue?

**Comment by egonw** [comment]
Ah, ok, both of those suggested commands give errors too, so it seems I have a broken npm installation.
