### ISSUE TITLE
ShEx Loader + Validator example in Readme is broken

### ISSUE THREAD

**Issue by micgro42** [shexSpec/shex.js#50]
The example given in the Readme for how to use the Loader and Validator, seems broken. It throws the following error:
```
Uncaught (in promise) TypeError: db.getNeighborhood is not a function
    at ShExValidator_constructor._validateShape (shex-webapp-webpack.js:51591)
    at ShExValidator_constructor._validateShapeExpr (shex-webapp-webpack.js:51539)
    at ShExValidator_constructor.validate (shex-webapp-webpack.js:51505)
    at shex-test.html:19
```
It seems to be thrown at https://github.com/shexSpec/shex.js/blob/17756428852d9abb1d5242f539675265ea38395a/packages/shex-core/lib/ShExValidator.js#L474

I also receive this error in the version build with the npm package, where it is thrown at https://github.com/shexSpec/shex.js/blob/6709a8dc8ca9e19397aeea52cc898ec2e31d6cb7/packages/shex-core/lib/ShExValidator.js#L583

You can reproduce this by putting the following html file next to `shex-simple.html` in `packages/shex-webapp/doc/` and opening it.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Minimal failing example</title>
</head>
<body>
<script src="../browser/shex-webapp-webpack.js"></script>
<script>

	var shex = ShExWebApp; // @@ rename globally
	var shexc = "http://shex.io/examples/Issue.shex";
	var shape = "http://shex.io/examples/IssueShape";
	var data = "http://shex.io/examples/Issue1.ttl";
	var node = "http://shex.io/examples/Issue1";

	shex.Loader.load([shexc], [], [data], []).then(function (loaded) {
		console.log(shex.Validator.construct(loaded.schema).validate(loaded.data, node, shape));
	});
</script>
</body>
</html>
```

Am I doing something wrong?

**Comment by ericprud** [comment]
You need to have `shex.Util.makeN3DB(loaded.data)` around "loaded.data". This returns a wrapper around the triple store with a function called `getNeighborhood()`. Since this is no longer specific to N3.js, I need a better name for that function. N3.js now follows the [RDFJS dataset spec](https://rdf.js.org/dataset-spec/) so maybe a better name is `makeDataset(db)`. Something like `fromDataset(db)` would look good from a literate programming perspective but wouldn't really say what it does. Advice?

**Comment by micgro42** [comment]
Thanks, I will have a closer look at this tonight or over the coming days.

Unfortunately, my knowledge of this domain is very limited. But I will try to see if one of the names feels more intuitive to me :)

**Comment by micgro42** [comment]
Greetings from the Wikimedia Hackathon in Prague 👋

Thank you, with that extra call it isn't throwing any errors anymore. But the validation results are still wrong :/

In the example below, I have a schema that verifies 
1. that the item is instance of house cat
2. that the item has a birthday property

It is provided with the data for the cat [Toffee](https://www.wikidata.org/wiki/Q49581026), which should pass that validation (see [simple shex evaluation](https://rawgit.com/shexSpec/shex.js/wikidata/packages/shex-webapp/doc/shex-simple.html?schema=PREFIX%20wd%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0APREFIX%20wdt%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E%0APREFIX%20p%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2F%3E%0APREFIX%20prov%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fprov%23%3E%0APREFIX%20pq%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fqualifier%2F%3E%0APREFIX%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0APREFIX%20prv%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Freference%2Fvalue%2F%3E%0APREFIX%20pr%3A%20%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Freference%2F%3E%0APREFIX%20ps%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fstatement%2F%3E%0A%0Astart%20%3D%20%40%3Cwikidata-cat%3E%0A%0A%3Cwikidata-cat%3E%20%7B%20%20%20%20%0A%09%23%23%20STATEMENTS%0A%09p%3AP31%20%40%3CP31_instance_of_house_cat%3E%20%3B%0A%20%20%20%20%20%20%20%20p%3AP569%20.%0A%7D%20%0A%0A%23%20Shape%20expression%20for%20Wikidata%20statements%0A%3CP31_instance_of_house_cat%3E%20%7B%0A%09%20ps%3AP31%20%5Bwd%3AQ146%5D%20%3B%20%0A%7D&data=%0A%0A%20%20Endpoint%3A%20https%3A%2F%2Fquery.wikidata.org%2Fsparql%0A&manifestURL=..%2Fexamples%2Fmanifest.json&shape-map=%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ49581026%3E%40START&interface=human&regexpEngine=threaded-val-nerr)). But it gives a failure that the two properties are missing. It feels like I still miss a call to add the triples (quads?) to the data before it is validated. Any advice?

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Minimal failing example</title>
</head>
<body>
<script src="../browser/shex-webapp-webpack.js"></script>
<script>

	var shex = ShExWebApp; // @@ rename globally
	var shexc = "https://wikidata-shex.wmflabs.org/wiki/Special:EntitySchemaText/E3";
	var shape = "https://wikidata-shex.wmflabs.org/wiki/Special:EntitySchemaText/wikidata-cat";
	var data = "https://www.wikidata.org/wiki/Special:EntityData/Q49581026.ttl";
	var node = "https://www.wikidata.org/wiki/Special:EntityData/Q49581026";

	shex.Loader.load([shexc], [], [data], []).then(function (loaded) {
		const db = shex.Util.makeN3DB(loaded.data);
		console.log(shex.Validator.construct(loaded.schema).validate(db, node, loaded.schema.start));
	});
</script>
</body>
</html>
```

About the naming: It should include _what_ is made and maybe also from what (since there are no types): `makeXFromY(...)`. Also, don't be concerned about the length of the name. Better a bit longer and explicit than short and too cryptic. This is especially true as the method name is currently the only documentation that there is for the API.
That being said, the examples in the readme is quite useful. Once we get it working I'll make a PR to update the docs :)

**Comment by micgro42** [comment]
Got it via stepping through the code with the debugger in parallel and looking at what is going on. The following HTML gives the correct results:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Minimal failing example</title>
</head>
<body>
<script src="../browser/shex-webapp-webpack.js"></script>
<script>
	var shex = ShExWebApp; // @@ rename globally
	var shexc = "https://wikidata-shex.wmflabs.org/wiki/Special:EntitySchemaText/E3";
	var shape = "https://wikidata-shex.wmflabs.org/wiki/Special:EntitySchemaText/wikidata-cat";
	var data = "https://www.wikidata.org/wiki/Special:EntityData/Q49581026.ttl";
	var node = "http://www.wikidata.org/entity/Q49581026";

	shex.Loader.load([shexc], [], [data], []).then(function (loaded) {
		const db = shex.Util.makeN3DB(loaded.data);
		const validator = shex.Validator.construct(loaded.schema, { results: "api" });
		const result = validator.validate(db, [{node, shape: shex.Validator.start}]);
		console.log(result);
	});
</script>
</body>
</html>
```
🙌

That being said, I still don't fully understand _why_ it works. Especially, the significance of the changed `node` url is totally not clear to me.
But anyway, this should get me going with my actual project 😀
Tomorrow, I'll make a pull request to update the Readme as promised.
