### ISSUE TITLE
catch shex.Loader.load() errors

### ISSUE THREAD

**Issue by scenaristeur** [shexSpec/shex.js#61]
Hi,
I'd like to know if there is a way to catch shex.Loader.load() errors. 
or parser errors. 
I'm trying to generate forms-ui from a shex shape as discussed here 
https://forum.solidproject.org/t/from-shape-to-form-experiments-with-shex-shacl/2027
based on Ruben' post 
https://forum.solidproject.org/t/blog-post-shaping-linked-data-apps/1914 and more https://ruben.verborgh.org/blog/2019/06/17/shaping-linked-data-apps/

So I've tried to parse .shex myself but it's hard, so I tried shex.js 
and it's working quite good as you can see here https://scenaristeur.github.io/spoggy-simple/testform.html

But I've got some mistake with two of my shex. Perharps are they malformatted but I don't know what is the mistake (the manner I implemente the Choice ? )

For all the shex, it runs, but  when I choose 
https://holacratie.solid.community/public/Schema/purpose.shex or https://holacratie.solid.community/public/Schema/domaine.shex

Nothing happens, 

I've tried to test the loaded.schema  https://github.com/scenaristeur/spoggy-simple/blob/020548ff707c6f171d1dcf7d72788cabc0d91a57/testform.html#L93

but nothing happens . 

So I wonder if it could be possible to catch a loading/parsing error . 

+ if you have an idea with what could be wrong in purpose.shex & domain.shex, I'd be really thankfull 
 ;-)

**Comment by scenaristeur** [comment]
I got it . 
```
    shex.Loader.load([shapeUrl], [], [], []).then(loaded => {
      console.log("LOADED",loaded)
      if (loaded.schema){
        log(shapeUrl, "schema loaded")
        //  schemaToForm(loaded.schema)
      }
    }
    , err => {
      log(err, "ERROR when loading schema")
    }
  )
```

Sorry

**Comment by ericprud** [comment]
Oops. sorry I wasn't more help. Yeah, the loader just returns an ES5 Promise. If you'd like to improve the Loader interface, let me know.
